<?php

/**
 * Implements hook_page_build().
 */
function authcache_statistics_page_build() {
//  if ($node && variable_get('statistics_count_content_views', 0)) {
//    // need to extract that logic into a node-preprocess function (views-counter);
//  }

  $settings = array(
    'log' => FALSE,
  );

  if (variable_get('statistics_enable_access_log', 0)) {
    $settings['log'] = TRUE;
  }

  authcache_ajax_add_command('statistics');
  drupal_add_js(drupal_get_path('module', 'authcache_statistics') . '/authcache_statistics.js');
  drupal_add_js(array('authcacheStatistics' => $settings), 'setting');
}

/**
 * Implements hook_module_implements_alter().
 *
 * Ensure that statistics_exit is never invoked. We call it exclusively
 * from the ajax phase.
 */
function authcache_statistics_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'exit') {
    unset($implementations['statistics']);
  }
}

/**
 * Implements hook_authcache_menu_item_cacheable().
 */
function authcache_statistics_authcache_menu_item_cacheable() {
  $items['user/%/track/navigation'] = TRUE;
  $items['node/%/track'] = TRUE;

  return $items;
}

/**
 * Implements hook_authcache_ajax_command().
 */
function authcache_statistics_authcache_ajax_command() {
  return array(
    'statistics' => array(
      'handler' => 'AuthcacheStatisticsUpdateCommand',
      'request config' => array(
        'q' => TRUE,
      ),
    ),
  );
}
